### PR TITLE
Do not crash parser on invalid URL

### PR DESCRIPTION
**Pull request by gugu**
Currently this module crashes the app if URL is invalid. This will just return nil

### CODE REVIEW

**Comment by snowplowcla** [comment]
Thanks for your pull request. Is this your first contribution to a Snowplow open source project? Before we can look at your pull request, you'll need to sign a Contributor License Agreement (CLA).

:memo: Please visit https://github.com/snowplow/snowplow/wiki/CLA to learn more and sign.

Once you've signed, please reply here (e.g. I signed it!) and we'll verify. Thanks.

**Comment by gugu** [comment]
I signed it

**Comment by snowplowcla** [comment]
Confirmed! @gugu has signed the Contributor License Agreement. Thanks so much.

**Review by BenFradet — APPROVED** [review]
:+1:

**Pull request merged**
